# Generated by Django 5.1.6 on 2025-02-26 14:54

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "airport",
            "0003_alter_airplane_airplane_type_alter_route_destination_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.airplane_image_file_path
            ),
        ),
    ]
